sites:
  - name: Warsaw
    facility: lab
    status: Staging

manufacturers:
  - Cisco
  - Arista
  - Juniper

device_types:
  - model: 'Cisco Router'
    manufacturer: 'Cisco'
  - model: 'Cisco Switch'
    manufacturer: â€œCisco'
  - model: 'Arista Switch'
    manufacturer: 'Arista'
  - model: 'Juniper Switch'
    manufacturer: 'Juniper'

device_roles: 
  - name: 'lab device'
    color: FFFFFF